
"@context":

ontologies:

## HCAO

  - id: hcao
    preferredPrefix: HCA
    title: Human Cell Atlas Ontology
    uri: http://schema.humancellatlas.org/ontology/hcao.owl
    base_uri:
      - http://schema.humancellatlas.org/ontology/HCA_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://github.com/HumanCellAtlas/ontology/raw/master/hcao.owl

## HCAO simple

  - id: hcaos
    preferredPrefix: HCA
    title: Human Cell Atlas Ontology (simple)
    uri: http://schema.humancellatlas.org/ontology/hcao-simple.owl
    base_uri:
      - http://schema.humancellatlas.org/ontology/HCA_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://github.com/HumanCellAtlas/ontology/raw/master/hcao-simple.owl

