
"@context":

ontologies:

## CHEM

  - id: chem
    preferredPrefix: CHEM
    title: CHEM
    uri: http://purl.obolibrary.org/obo/chem.owl
    base_uri:
      - http://purl.obolibrary.org/obo/CHEM_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/simonjupp/chem_ontology/master/chem.owl

## PLIV

  - id: pliv
    preferredPrefix: PLIV
    title: PLIV
    uri: http://purl.obolibrary.org/obo/pliv.owl
    base_uri:
      - http://purl.obolibrary.org/obo/PLIV_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/simonjupp/pliv_ontology/master/pliv.owl

## AMPH

  - id: amph
    preferredPrefix: AMPH
    title: AMPH
    uri: http://purl.obolibrary.org/obo/amph.owl
    base_uri:
      - http://purl.obolibrary.org/obo/AMPH_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/simonjupp/amph_ontology/master/amph.owl
