"@context":

ontologies:

## CHEM

  - id: chem
    preferredPrefix: CHEM
    title: CHEM
    uri: http://purl.obolibrary.org/obo/chem.owl
    base_uri:
      - http://purl.obolibrary.org/obo/CHEM_
    reasoner: EL
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/simonjupp/chem_ontology/master/chem.owl
